SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Auction_DeleteLot
	@ID int
as
BEGIN
	SET	NOCOUNT ON;
	DELETE FROM Lots WHERE ID = @ID
	DELETE FROM UsersToLots WHERE LotID = @ID
END
