SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE Auction_DeleteUser
	@ID int
as
BEGIN
	SET	NOCOUNT OFF;
	DELETE FROM AccountDetails WHERE ID = @ID
	DELETE FROM Users WHERE ID = @ID
	DELETE FROM AccountsToRole WHERE AccountID = @ID
	DELETE FROM UsersToLots WHERE UserID = @ID
END